/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/AnimatedAnchor")]
    [LuaRegisterType(0xe829075ce83bf54d, typeof(LuaBehaviour))]
    public class AnimatedAnchor : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b065abe2e2b7d3e4ab4dccfe48671dbb";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_enterTriggerName = "";
        [SerializeField] public System.String m_exitTriggerName = "";
        [SerializeField] public System.Boolean m_randomizeStartIdle = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_enterTriggerName),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_exitTriggerName),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_randomizeStartIdle),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/AnimatedAnchor/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
