/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/AudioManager")]
    [LuaRegisterType(0x54ef1694c40a5ef8, typeof(LuaBehaviour))]
    public class AudioManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "56e97f8baee632d4083a89ef9e959075";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_BGMusic = default;
        [SerializeField] public Highrise.AudioShader m_BossLoop = default;
        [SerializeField] public Highrise.AudioShader m_HoldVibrateShader = default;
        [SerializeField] public Highrise.AudioShader m_popSound = default;
        [SerializeField] public Highrise.AudioShader m_shimmer = default;
        [SerializeField] public Highrise.AudioShader m_laughSound = default;
        [SerializeField] public Highrise.AudioShader m_springSound = default;
        [SerializeField] public Highrise.AudioShader m_leavesSound = default;
        [SerializeField] public Highrise.AudioShader m_rewardExplosionSound = default;
        [SerializeField] public Highrise.AudioShader m_spawnSparkleSound = default;
        [SerializeField] public Highrise.AudioShader m_ghostSqueakSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_BGMusic),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_BossLoop),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_HoldVibrateShader),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_popSound),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_shimmer),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_laughSound),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_springSound),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_leavesSound),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_rewardExplosionSound),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_spawnSparkleSound),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_ghostSqueakSound),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/AudioManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
