/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CoinController")]
    [LuaRegisterType(0x8310a762376c1d3c, typeof(LuaBehaviour))]
    public class CoinController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9c5b6b01d5d1b19408bc7ed45cfb621f";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.AnimationCurve m_positionCurve = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_positionCurve),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CoinController/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
