/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CollectRaffleTicket")]
    [LuaRegisterType(0x6de268c9d0704b27, typeof(LuaBehaviour))]
    public class CollectRaffleTicket : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3d551ca7e28eead488ab1934036e8979";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_ticketValue = 1;
        [SerializeField] public UnityEngine.GameObject m_popUPObj = default;
        [SerializeField] public UnityEngine.GameObject m_mainObj = default;
        [SerializeField] public UnityEngine.GameObject m_ticketObj = default;
        [SerializeField] public UnityEngine.GameObject m_particlesObj = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_ticketValue),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_popUPObj),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_mainObj),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_ticketObj),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_particlesObj),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CollectRaffleTicket/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
