/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CollectQuestManager")]
    [LuaRegisterType(0x2621fa11d4781bd8, typeof(LuaBehaviour))]
    public class CollectQuestManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e6afc9b40002fe8448c0333ff144d3ad";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("6ceb448de1206ec4c94893661d3b5508")]
        [SerializeField] public UnityEngine.Object m_questCountUI = default;
        [SerializeField] public UnityEngine.GameObject m_chatbubbles = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_questCountUI),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_chatbubbles),
            };
        }
    }
}

#endif
