/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CountdownTimer")]
    [LuaRegisterType(0x933c83c9f9a72eb1, typeof(LuaBehaviour))]
    public class CountdownTimer : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5086252910e534b6b9ef6fb451017f59";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("EST date-time for Event01 end, in 'YYYY-MM-DD HH:MM:SS'")]
        [SerializeField] public System.String m_event01EndTime = "2025-06-15 12:00:00";
        [Tooltip("EST date-time for Event02 start, in 'YYYY-MM-DD HH:MM:SS'")]
        [SerializeField] public System.String m_event02StartTime = "2025-06-15 18:00:00";
        [Tooltip("EST date-time for Event02 end, in 'YYYY-MM-DD HH:MM:SS'")]
        [SerializeField] public System.String m_event02EndTime = "2025-06-15 20:00:00";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_event01EndTime),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_event02StartTime),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_event02EndTime),
            };
        }
    }
}

#endif
