/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CountdownTimer")]
    [LuaRegisterType(0x933c83c9f9a72eb1, typeof(LuaBehaviour))]
    public class CountdownTimer : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5086252910e534b6b9ef6fb451017f59";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("List of local date-times for event starts in 'YYYY-MM-DD HH:MM:SS'")]
        [SerializeField] public System.Collections.Generic.List<System.String> m_eventStartTimes = default;
        [Tooltip("List of local date-times for event ends in 'YYYY-MM-DD HH:MM:SS'")]
        [SerializeField] public System.Collections.Generic.List<System.String> m_eventEndTimes = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_eventStartTimes),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_eventEndTimes),
            };
        }
    }
}

#endif
