/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CountdownTimerNext")]
    [LuaRegisterType(0x1d7a7b1adc1e5d9c, typeof(LuaBehaviour))]
    public class CountdownTimerNext : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a8ad35b0095cf4089bdb85061d62a05e";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_eventImages = default;
        [Tooltip("List of ET start times for each event in 'YYYY-MM-DD HH:MM:SS'")]
        [SerializeField] public System.Collections.Generic.List<System.String> m_eventStartTimes = default;
        [Tooltip("List of ET end times for each event in 'YYYY-MM-DD HH:MM:SS'")]
        [SerializeField] public System.Collections.Generic.List<System.String> m_eventEndTimes = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_eventImages),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_eventStartTimes),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_eventEndTimes),
            };
        }
    }
}

#endif
