/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CycleMarketplace")]
    [LuaRegisterType(0x808b12bf9c2f4f9c, typeof(LuaBehaviour))]
    public class CycleMarketplace : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3538d88fda9d74d75bbccbc7210b4c13";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Material m_Material = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_Textures = default;
        [SerializeField] public System.Collections.Generic.List<System.String> m_linkurls = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Material),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Textures),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_linkurls),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CycleMarketplace/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
