/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DeepLink")]
    [LuaRegisterType(0x9fa8454f40badc03, typeof(LuaBehaviour))]
    public class DeepLink : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "61c2013e3db47c9499258afe3b340c42";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_linkurl = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_linkurl),
            };
        }
    }
}

#endif
