/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/DialogueTextBlock")]
    [LuaRegisterType(0x1d7cd12b970ca68d, typeof(LuaScriptableObject))]
    public class DialogueTextBlock : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "56c23c95405296944a4c52a9bbff52ec";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_message = "";
        [SerializeField] public System.Double m_specialAnimationID = 0;
        [SerializeField] public UnityEngine.Color m_textColor = new Color(15f, 44f, 56f, 1f);

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_message),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_specialAnimationID),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_textColor),
            };
        }
    }
}

#endif
