/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/DialogueChunk")]
    [LuaRegisterType(0x8bd551d4e826ba40, typeof(LuaScriptableObject))]
    public class DialogueChunk : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "3d0bd200f8ab7b948aa8f0034f550645";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("5f7dbb76983dd93469a12bb278d8bb78")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_Pages = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Pages),
            };
        }
    }
}

#endif
