/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/DialoguePage")]
    [LuaRegisterType(0x3a23ac4294318728, typeof(LuaScriptableObject))]
    public class DialoguePage : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "5f7dbb76983dd93469a12bb278d8bb78";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("56c23c95405296944a4c52a9bbff52ec")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_Messages = default;
        [SerializeField] public System.Collections.Generic.List<System.String> m_responses = default;
        [SerializeField] public System.Collections.Generic.List<System.String> m_responseIDs = default;
        [LuaScriptPropertyAttribute("3d0bd200f8ab7b948aa8f0034f550645")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_Chunks = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Messages),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_responses),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_responseIDs),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_Chunks),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/DialoguePage/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
