/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DialogueResponseManager")]
    [LuaRegisterType(0xe76a8814edc4e87f, typeof(LuaBehaviour))]
    public class DialogueResponseManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a68ee8cb4b8e37d42af701f40484114f";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("49cb00da31d223d429d8add9b96c16aa")]
        [SerializeField] public UnityEngine.Object _DialogueCameraController = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _DialogueCameraController),
            };
        }
    }
}

#endif
