/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EmoteScript")]
    [LuaRegisterType(0x5309c7a3df721fc4, typeof(LuaBehaviour))]
    public class EmoteScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b602bbfe5c5f3414ca9a9911aaa76853";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<System.String> m_emote_ids = default;
        [SerializeField] public System.Boolean m_is_loop = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_emote_ids),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_is_loop),
            };
        }
    }
}

#endif
