/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EventInfo")]
    [LuaRegisterType(0xf463c5f2f91b82ab, typeof(LuaBehaviour))]
    public class EventInfo : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "53c9994923422e64990a9fa1214955fd";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture m_custom_currency_Icon = default;
        [SerializeField] public UnityEngine.Texture m_default_container_Icon = default;
        [SerializeField] public UnityEngine.Texture m_progressBarGrowthParticleRenderTexture = default;
        [SerializeField] public UnityEngine.GameObject m_progressBarGrowthParticleVirtualScene = default;
        [SerializeField] public Highrise.AudioShader m_openCardSound = default;
        [SerializeField] public Highrise.AudioShader m_closeCardSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_custom_currency_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_default_container_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_progressBarGrowthParticleRenderTexture),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_progressBarGrowthParticleVirtualScene),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_openCardSound),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_closeCardSound),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
                CreateSerializedProperty(_script.GetPropertyAt(9), null),
                CreateSerializedProperty(_script.GetPropertyAt(10), null),
                CreateSerializedProperty(_script.GetPropertyAt(11), null),
                CreateSerializedProperty(_script.GetPropertyAt(12), null),
                CreateSerializedProperty(_script.GetPropertyAt(13), null),
                CreateSerializedProperty(_script.GetPropertyAt(14), null),
                CreateSerializedProperty(_script.GetPropertyAt(15), null),
                CreateSerializedProperty(_script.GetPropertyAt(16), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/EventInfo/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
