/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EventHUDDisplay")]
    [LuaRegisterType(0x80836bfdf6b73f52, typeof(LuaBehaviour))]
    public class EventHUDDisplay : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fa83d1dbb554c4ae78a8b69f70c1bff7";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Material m_Material = default;
        [Tooltip("Assign a ScriptableObject of type EventsScriptableObject (with public fields GetEventStartDates() and GetEventHuds()) here")]
        [LuaScriptPropertyAttribute("a93c703b1c5df4993a31682ed7594753")]
        [SerializeField] public UnityEngine.Object m_Events_ScriptableObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Material),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Events_ScriptableObject),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/EventHUDDisplay/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
