/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Events_CountdownTimer")]
    [LuaRegisterType(0xca1e8388de257a95, typeof(LuaBehaviour))]
    public class Events_CountdownTimer : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8e48b73e82417416792ffd7cba53a3e1";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Assign a ScriptableObject of type MarqueeEventsSO (with public fields GetEventStartDates() and GetEventImages()) here")]
        [LuaScriptPropertyAttribute("a93c703b1c5df4993a31682ed7594753")]
        [SerializeField] public UnityEngine.Object m_Events_ScriptableObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_Events_ScriptableObject),
            };
        }
    }
}

#endif
