/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EventsTimer_Countdown")]
    [LuaRegisterType(0x5e5669572d362c4d, typeof(LuaBehaviour))]
    public class EventsTimer_Countdown : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e73f4442a8129408187f24f573be7f4c";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Assign a ScriptableObject of type MarqueeEventsSO (with public fields GetEventStartDates() and GetEventImages()) here")]
        [LuaScriptPropertyAttribute("a93c703b1c5df4993a31682ed7594753")]
        [SerializeField] public UnityEngine.Object m_Events_ScriptableObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_Events_ScriptableObject),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/EventsTimer_Countdown/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
