/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/Events_ScriptableObject")]
    [LuaRegisterType(0xa92f6594dede999, typeof(LuaScriptableObject))]
    public class Events_ScriptableObject : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "a93c703b1c5df4993a31682ed7594753";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_grabBanners = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_eventHuds = default;
        [SerializeField] public System.Collections.Generic.List<System.String> m_eventStartDates = default;
        [SerializeField] public System.Collections.Generic.List<System.String> m_eventNames = default;
        [SerializeField] public System.Collections.Generic.List<System.String> m_grabLinkUrls = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_grabBanners),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_eventHuds),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_eventStartDates),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_eventNames),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_grabLinkUrls),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/Events_ScriptableObject/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
