/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GrabsTimedObject")]
    [LuaRegisterType(0x6525bef210609b48, typeof(LuaBehaviour))]
    public class GrabsTimedObject : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "945dc513ae11b4183988fcb55dee5cb1";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_objects = default;
        [Tooltip("List of ET start times for each event in 'YYYY-MM-DD HH:MM:SS'")]
        [SerializeField] public System.Collections.Generic.List<System.String> m_eventStartTimes = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_objects),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_eventStartTimes),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/GrabsTimedObject/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
