/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/HRLive_ComingUpSign")]
    [LuaRegisterType(0x47a56edadab5141d, typeof(LuaBehaviour))]
    public class HRLive_ComingUpSign : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "111c8dd68e1d2490caec9dc076e8af6e";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Assign a ScriptableObject of type MarqueeEventsSO (with a public Texture[] field named 'textures') here")]
        [LuaScriptPropertyAttribute("af13bcdc730f242c0a6701194b971b13")]
        [SerializeField] public UnityEngine.Object m_marqueeEventsSO = default;
        [Tooltip("TextAsset containing one EST date/time per line ('YYYY-MM-DD HH:MM:SS')")]
        [SerializeField] public UnityEngine.TextAsset m_datesTextAsset = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_marqueeEventsSO),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_datesTextAsset),
            };
        }
    }
}

#endif
