/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/HRLiveMarqueeNew")]
    [LuaRegisterType(0xcf783f63dfb4337b, typeof(LuaBehaviour))]
    public class HRLiveMarqueeNew : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "70985b3efbe1649fe81e536c83a90719";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Assign a ScriptableObject of type MarqueeEventsSO (with a public Texture[] field named 'textures') here")]
        [LuaScriptPropertyAttribute("af13bcdc730f242c0a6701194b971b13")]
        [SerializeField] public UnityEngine.Object m_marqueeEventsSO = default;
        [Tooltip("TextAsset containing ET start times, one per line ('YYYY-MM-DD HH:MM:SS')")]
        [SerializeField] public UnityEngine.TextAsset m_startDatesTextAsset = default;
        [Tooltip("TextAsset containing ET end times, one per line ('YYYY-MM-DD HH:MM:SS')")]
        [SerializeField] public UnityEngine.TextAsset m_endDatesTextAsset = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_marqueeEventsSO),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_startDatesTextAsset),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_endDatesTextAsset),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/HRLiveMarqueeNew/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
