/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/HRLiveBannerManager")]
    [LuaRegisterType(0x45ab601976f1e4e6, typeof(LuaBehaviour))]
    public class HRLiveBannerManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "13dea1c772c6e0443a4df5c060db48ad";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_LiveEventLinkObj = default;
        [SerializeField] public System.String m_defaultStartDate = "2025-06-09 13:00:00";
        [SerializeField] public System.String m_defaultEndDate = "2025-06-09 15:00:00";
        [SerializeField] public System.String m_defaultBannerURL = "https://cdn.highrisegame.com/HRLiveEventBanners/WO_06_09_2025/01.png";
        [SerializeField] public System.String m_defaultRoomLink = "https://high.rs/room?id=6476fe22eeafcd5d47b38298";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_LiveEventLinkObj),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_defaultStartDate),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_defaultEndDate),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_defaultBannerURL),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_defaultRoomLink),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/HRLiveBannerManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
