/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/NpcDialogueController")]
    [LuaRegisterType(0x3f3d2120405e155e, typeof(LuaBehaviour))]
    public class NpcDialogueController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "db83d008c4b77b946a3d01f762eddf82";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_dialogueUIObject = default;
        [SerializeField] public UnityEngine.Color m_npcColor = new Color(157f, 56f, 187f, 1f);
        [SerializeField] public System.String m_npcName = "NPC";
        [LuaScriptPropertyAttribute("3d0bd200f8ab7b948aa8f0034f550645")]
        [SerializeField] public UnityEngine.Object m_startChunk = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_dialogueUIObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_npcColor),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_npcName),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_startChunk),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/NpcDialogueController/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
