/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PetCharacterControllerTemp")]
    [LuaRegisterType(0xf4438d708d2c590f, typeof(LuaBehaviour))]
    public class PetCharacterControllerTemp : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "90f05063c6701884d88404df3e28bdca";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject _characterPrefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _characterPrefab),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PetCharacterControllerTemp/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
