/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RaffleUIManager")]
    [LuaRegisterType(0xd9083aeea4b6c058, typeof(LuaBehaviour))]
    public class RaffleUIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "afad9aa65cf5a8741ab3248ae72946e4";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_mainRaffleUIObj = default;
        [SerializeField] public UnityEngine.GameObject m_infoUIObj = default;
        [SerializeField] public UnityEngine.GameObject m_winnerNotifObj = default;
        [SerializeField] public UnityEngine.GameObject m_winnerParticleObj = default;
        [SerializeField] public UnityEngine.GameObject m_sparklesOneshotObj = default;
        [SerializeField] public UnityEngine.GameObject m_resultsObj = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_mainRaffleUIObj),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_infoUIObj),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_winnerNotifObj),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_winnerParticleObj),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_sparklesOneshotObj),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_resultsObj),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/RaffleUIManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
