/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RaffleManager")]
    [LuaRegisterType(0xbd0da47129a6d35a, typeof(LuaBehaviour))]
    public class RaffleManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "267007cf403ffa14a90907d033dcd110";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("e608c7a1a7ccd654ab05e9dcacd725ea")]
        [SerializeField] public UnityEngine.Object m_raffleUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_raffleUI),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/RaffleManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
