/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RandomMessageLoop_Tips")]
    [LuaRegisterType(0xa7b5829b235215b2, typeof(LuaBehaviour))]
    public class RandomMessageLoop_Tips : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1bb9879b7cbd7477dbccddec0e6cc901";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_emoteId = "emote-hello";
        [SerializeField] public System.Double m_messageInterval = 15;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_emoteId),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_messageInterval),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/RandomMessageLoop_Tips/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
