/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RTSUIMapMenu")]
    [LuaRegisterType(0x5917bacd091378f3, typeof(LuaBehaviour))]
    public class RTSUIMapMenu : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e54e87a7edd514595a71c717e356e2f5";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture m_MapImage = default;
        [SerializeField] public UnityEngine.Transform m_MarketPostion = default;
        [SerializeField] public UnityEngine.Transform m_ShopPosition = default;
        [SerializeField] public UnityEngine.Transform m_WelcomePosition = default;
        [SerializeField] public UnityEngine.Transform m_TownHallPosition = default;
        [SerializeField] public UnityEngine.Transform m_EventsPosition = default;
        [SerializeField] public UnityEngine.Transform m_ParkPosition = default;
        [SerializeField] public UnityEngine.Transform m_ArtCenterPosition = default;
        [SerializeField] public UnityEngine.Transform m_BuilderCenterPosition = default;
        [SerializeField] public UnityEngine.Transform m_TrasitStationPosition = default;
        [SerializeField] public UnityEngine.Transform m_HRLivePosition = default;
        [SerializeField] public UnityEngine.Transform m_PicnicPosition = default;
        [SerializeField] public UnityEngine.Transform m_StatuePosition = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
                CreateSerializedProperty(_script.GetPropertyAt(9), null),
                CreateSerializedProperty(_script.GetPropertyAt(10), null),
                CreateSerializedProperty(_script.GetPropertyAt(11), null),
                CreateSerializedProperty(_script.GetPropertyAt(12), null),
                CreateSerializedProperty(_script.GetPropertyAt(13), null),
                CreateSerializedProperty(_script.GetPropertyAt(14), null),
                CreateSerializedProperty(_script.GetPropertyAt(15), null),
                CreateSerializedProperty(_script.GetPropertyAt(16), null),
                CreateSerializedProperty(_script.GetPropertyAt(17), null),
                CreateSerializedProperty(_script.GetPropertyAt(18), m_MapImage),
                CreateSerializedProperty(_script.GetPropertyAt(19), m_MarketPostion),
                CreateSerializedProperty(_script.GetPropertyAt(20), m_ShopPosition),
                CreateSerializedProperty(_script.GetPropertyAt(21), m_WelcomePosition),
                CreateSerializedProperty(_script.GetPropertyAt(22), m_TownHallPosition),
                CreateSerializedProperty(_script.GetPropertyAt(23), m_EventsPosition),
                CreateSerializedProperty(_script.GetPropertyAt(24), m_ParkPosition),
                CreateSerializedProperty(_script.GetPropertyAt(25), m_ArtCenterPosition),
                CreateSerializedProperty(_script.GetPropertyAt(26), m_BuilderCenterPosition),
                CreateSerializedProperty(_script.GetPropertyAt(27), m_TrasitStationPosition),
                CreateSerializedProperty(_script.GetPropertyAt(28), m_HRLivePosition),
                CreateSerializedProperty(_script.GetPropertyAt(29), m_PicnicPosition),
                CreateSerializedProperty(_script.GetPropertyAt(30), m_StatuePosition),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/RTSUIMapMenu/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
