/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ServerPrankModule")]
    [LuaRegisterType(0x2a364a61b37e61a8, typeof(LuaBehaviour))]
    public class ServerPrankModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "0246a48c7afcf2840a115aaa09975ca9";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_testMode = false;
        [SerializeField] public System.String m_apiEndpoint = "http://hangout-private-lb-liveops-614010634fd20aaa.elb.us-east-1.amazonaws.com";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_testMode),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_apiEndpoint),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/ServerPrankModule/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
