/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Spawner")]
    [LuaRegisterType(0x26f94bf11aa54a8f, typeof(LuaBehaviour))]
    public class Spawner : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "7fd3337a202cd8a4b9512e1a0870e3b8";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_collectibleObject = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Transform> m_startSpawnPositions = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Transform> m_endSpawnPositions = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_collectibleObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_startSpawnPositions),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_endSpawnPositions),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/Spawner/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
