/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/StorageManager")]
    [LuaRegisterType(0x508909bc43dd2a85, typeof(LuaBehaviour))]
    public class StorageManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9181b161f2f2347dca36c2e7fa0f209d";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_defaultBannerURL = "https://cdn.highrisegame.com/trivia_venice.png";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_defaultBannerURL),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/StorageManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
