/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TicketAPI")]
    [LuaRegisterType(0xa9a7ae18ec8b21a7, typeof(LuaBehaviour))]
    public class TicketAPI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8f92d4a1d1ce39e4ba86b70b479c6356";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_WorldID = "673221da832dd03de843b8fc";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_WorldID),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/TicketAPI/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
