/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TicTacToeTileScript")]
    [LuaRegisterType(0x19cebb229977cd9c, typeof(LuaBehaviour))]
    public class TicTacToeTileScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b37b50d6dff7d1e479f98d6bbdaf7646";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_X = default;
        [SerializeField] public UnityEngine.GameObject m_O = default;
        [SerializeField] public Highrise.Client.Anchor m_anchor1 = default;
        [SerializeField] public Highrise.Client.Anchor m_anchor2 = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_X),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_O),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_anchor1),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_anchor2),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/TicTacToeTileScript/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
