/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TimedObject_Emotes")]
    [LuaRegisterType(0xd63ef31fa7014519, typeof(LuaBehaviour))]
    public class TimedObject_Emotes : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3df31ed87e7d14dc0b311c5bb35eb437";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_objectA = default;
        [SerializeField] public UnityEngine.GameObject m_objectB = default;
        [SerializeField] public System.String m_baseStartTime = "2025-06-10 12:00:00";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_objectA),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_objectB),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_baseStartTime),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/TimedObject_Emotes/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
