/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TimedObjects_WithLink")]
    [LuaRegisterType(0xad56948b300b4461, typeof(LuaBehaviour))]
    public class TimedObjects_WithLink : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1c6a26b2ed16745939fa1871f63e0dc8";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_objects = default;
        [SerializeField] public UnityEngine.TextAsset m_startTimesFile = default;
        [SerializeField] public UnityEngine.TextAsset m_endTimesFile = default;
        [SerializeField] public UnityEngine.TextAsset m_linkUrlsFile = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_objects),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_startTimesFile),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_endTimesFile),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_linkUrlsFile),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/TimedObjects_WithLink/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
