/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIMapButton")]
    [LuaRegisterType(0xb349a03fd02b85b3, typeof(LuaBehaviour))]
    public class UIMapButton : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e395a59dc9d004d75aae1020e7bb80bb";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture m_MapImage = default;
        [SerializeField] public UnityEngine.GameObject m_MapMenuUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_MapImage),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_MapMenuUI),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/UIMapButton/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
